---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    condition: "{{status}}"
    query1: "results[?(@.started>='{{start_date}}')]"
    query2: "[?(@.started<='{{end_date}}')]"
  tasks:
    - name: "Get the Jobs"
      uri:
        url: "http://35.244.8.160:8080/api/v2/jobs/?status={{condition}}"
        method: GET
        headers:
          Authorization: Bearer f7DZhaZPWPdirC6ErCnfwfImEp8xpn
      register: jobs
    - set_fact:
        jobs_filter: "{{ jobs.json | json_query(query1)}}"
    - set_fact:
        final_result: "{{ jobs_filter | json_query(query2)}}"
    - set_fact:
        count1: "{{final_result | count}}"

    - name: "set the id"
      set_fact:
        ID: "{{final_result[item | int - 1]['id']}}"
      with_sequence: count="{{count1 | int}}"
      register: ID_Result
    - debug:
        msg: "{{ID_Result.results[item | int -1]['ansible_facts']['ID']}}"
      with_sequence: count="{{count1 | int}}"
